#!/bin/bash
# Noah Bliss
# Initially based on a script by Shawn Rose <shawnandrewrose@gmail.com> found here: https://bbs.archlinux.org/viewtopic.php?id=230948

build() {
    add_module "tpm_crb"
    add_module "tpm_tis"
    add_module "tpm_tis_core"
    add_binary "/usr/lib/libtss2-tcti-device.so"
    add_module "tpm"
    add_binary "tpm2_unseal"
    add_binary "tpm2_load"
    #add_binary "clevis-decrypt-http"
    add_binary "clevis-decrypt-tang"
    add_binary "clevis-decrypt-sss"
    add_binary "clevis-decrypt"
    add_binary "clevis-decrypt-tpm2"
    add_binary "tpm2_createprimary"
    add_binary "luksmeta"
    add_binary "clevis"
    add_binary "jose"
    add_binary "curl"
    add_binary "bash"
    add_binary "tr"
    #Future-proofing for tpm2-tools v4
    tpm2_pcrget_bin=$(command -v tpm2_pcrlist)
    if [ -z "$tpm2_pcrget_bin" ]; then tpm2_pcrget_bin=$(command -v tpm2_pcrread); fi
    if [ -z "$tpm2_pcrget_bin" ]; then die 1 "Unable to find a tpm2 bin to read pcrs."; fi
    add_binary "${tpm2_pcrget_bin}" 
    add_runscript
}

help() {
    cat <<HELPEOF
This hook will attempt to unlock LUKS volumes using data stored in the header
by clevis and luksmeta. Use this hook in combination with any early userspace
networking hook, such as mkinitcpio-netconf or mkinitcpio-ppp. It also requires
mkinitcpio-utils for the encryptssh hook.

An example usage would be to have 'netconf mortar encryptssh' added before your
filesystems hook. Refer to the mortar documentation for further direction if needed.  
HELPEOF
}
